require "tnirpps.options"
require "tnirpps.keymaps"
require "tnirpps.plugins"
require "tnirpps.colorscheme"
require "tnirpps.cmp"
require "tnirpps.lsp"
require "tnirpps.treesitter"
require "tnirpps.autopairs"
require "tnirpps.comment"
require "tnirpps.toggleterm"
require "tnirpps.nvim-tree"
-- vim.cmd "colorscheme lunaperche"
-- vim.cmd "colorscheme slate"
